[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rfml-uav"
version = "0.1.0"
description = "RFML-based UAV signal detection and identification"
authors = [{name = "Ivan Sova"}]
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
